import {
  BIOME_RULE_TYPES,
  CONNECTION_TYPES,
  FACTION_RULE_TYPES,
  GAME_MODES,
  GATE_PLACEMENTS,
  GUARD_REACTIONS,
  MAIN_OBJECT_PLACEMENTS,
  MAIN_OBJECT_TYPES,
  PLACEMENT_RULE_TYPES,
  PLAYER_REFS,
  ROAD_TARGET_TYPES,
  ROAD_TYPES,
} from "../rmg/enums.js";
import { WIN_CONDITION_PRESETS } from "../rmg/winConditions.js";
import type {
  EditorFieldEditLevel,
  EditorFieldMetadata,
  EditorFieldSourceStatus,
  EditorSchema,
  EditorSchemaSection,
  EditorSchemaSectionId,
} from "./editorSchemaTypes.js";

const WIN_CONDITION_PRESET_IDS = WIN_CONDITION_PRESETS.map((preset) => preset.id);

export const EDITOR_SCHEMA_SECTIONS = [
  {
    id: "templateSettings",
    label: "Template Settings",
    description: "Root-level template identity, mode, size, variants, global bans, and value overrides.",
    docRefs: ["docs/rmg-kb/schema/template-root.md", "docs/rmg-kb/schema/value-overrides.md", "docs/rmg-kb/schema/global-bans.md"],
  },
  {
    id: "gameRules",
    label: "Game Rules",
    description: "Root game rules copied into generated map settings before map content is placed.",
    docRefs: ["docs/rmg-kb/schema/game-rules.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
  },
  {
    id: "winConditions",
    label: "Win Conditions",
    description: "Named victory-condition presets and the low-level booleans/parameters they expand to.",
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
  },
  {
    id: "zones",
    label: "Zones",
    description: "Variant-local gameplay regions: ownership, terrain, content budgets, main objects, and sampled pool presets.",
    docRefs: ["docs/rmg-kb/schema/zone.md", "docs/rmg/zones.md"],
  },
  {
    id: "connections",
    label: "Connections",
    description: "Variant-local graph edges between zones, including gates, portals, guard behavior, and placement rules.",
    docRefs: ["docs/rmg-kb/schema/connection.md", "docs/rmg/connections.md"],
  },
  {
    id: "roads",
    label: "Roads",
    description: "Zone-local authored roads connecting crossroads, main objects, connections, and mandatory content.",
    docRefs: ["docs/rmg-kb/schema/road.md", "docs/rmg-kb/schema/road-target.md", "docs/rmg/roads.md"],
  },
  {
    id: "contentPools",
    label: "Content Pools",
    description: "Template-local pools, content lists, weighted RMG content entries, bans, and count-limit presets.",
    docRefs: [
      "docs/rmg-kb/schema/content-pool.md",
      "docs/rmg-kb/schema/content-list.md",
      "docs/rmg-kb/schema/content-count-limit-preset.md",
      "docs/rmg/content-pools.md",
    ],
  },
  {
    id: "mandatoryContent",
    label: "Mandatory Content",
    description: "Preset-driven objects that must be placed in a zone when selected by the template.",
    docRefs: ["docs/rmg-kb/schema/mandatory-content-preset.md", "docs/rmg-kb/schema/mandatory-content-entry.md", "docs/rmg/mandatory-content.md"],
  },
  {
    id: "compatibility",
    label: "Compatibility Fields",
    description: "Observed or source-mismatched fields that should round-trip, but should not be treated as proven generator controls.",
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md", "docs/rmg/validation-and-gaps.md"],
  },
] as const satisfies readonly EditorSchemaSection[];

function field(metadata: EditorFieldMetadata): EditorFieldMetadata {
  return metadata;
}

export const EDITOR_SCHEMA_FIELDS = [
  field({
    id: "template.name",
    section: "templateSettings",
    scope: "template",
    path: "name",
    label: "Template Name",
    kind: "localizedString",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Human-facing template name.",
    valueMeaning: "Can be a SID/localized string in official files; keep raw value stable for round-tripping.",
    sourceEvidence: ["RandomMapTemplate.name", "Official templates all define root names."],
    docRefs: ["docs/rmg-kb/schema/template-root.md"],
    mutation: "updateTemplateSettings",
    validation: { nonEmpty: true },
  }),
  field({
    id: "template.description",
    section: "templateSettings",
    scope: "template",
    path: "description",
    label: "Description",
    kind: "localizedString",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Human-facing template description.",
    valueMeaning: "Usually a localization SID or display text; does not affect generation.",
    sourceEvidence: ["RandomMapTemplate.description"],
    docRefs: ["docs/rmg-kb/schema/template-root.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "template.gameMode",
    section: "templateSettings",
    scope: "template",
    path: "gameMode",
    label: "Game Mode",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Selects major game mode behavior.",
    valueMeaning: "`Classic` supports normal hero hiring; `SingleHero` pairs with stricter hero-count settings in official templates.",
    sourceEvidence: ["RandomMapTemplate.gameMode", "GameMode enum in inspected source."],
    docRefs: ["docs/rmg-kb/schema/template-root.md", "docs/rmg-kb/schema/game-rules.md"],
    mutation: "updateTemplateSettings",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: GAME_MODES },
  }),
  field({
    id: "template.displayWinCondition",
    section: "templateSettings",
    scope: "template",
    path: "displayWinCondition",
    label: "Displayed Win Condition",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "derived",
    description: "UI-facing preset name/SID shown for the template's win condition.",
    valueMeaning: "Should stay aligned with `gameRules.winConditions`, but the generator reads the low-level flags.",
    sourceEvidence: ["Official template displayWinCondition values match named win-condition presets.", "src/core/rmg/winConditions.ts"],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    picker: { source: "winConditionPresets", mode: "single" },
    validation: { allowedValues: WIN_CONDITION_PRESET_IDS },
  }),
  field({
    id: "template.sizeX",
    section: "templateSettings",
    scope: "template",
    path: "sizeX",
    label: "Map Width",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Map width in generator cells.",
    valueMeaning: "Positive integer controlling playable map dimensions.",
    sourceEvidence: ["RandomMapTemplate.sizeX"],
    docRefs: ["docs/rmg-kb/schema/template-root.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 1 },
  }),
  field({
    id: "template.sizeZ",
    section: "templateSettings",
    scope: "template",
    path: "sizeZ",
    label: "Map Height",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Map height in generator cells.",
    valueMeaning: "Positive integer controlling playable map dimensions.",
    sourceEvidence: ["RandomMapTemplate.sizeZ"],
    docRefs: ["docs/rmg-kb/schema/template-root.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 1 },
  }),
  field({
    id: "template.globalBans",
    section: "templateSettings",
    scope: "template",
    path: "globalBans",
    label: "Global Bans",
    kind: "object",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Template-wide bans for magic, items, skills, heroes, and units.",
    valueMeaning: "Lists contain Core SIDs to exclude from generation/hiring/availability.",
    sourceEvidence: ["RandomMapTemplate.globalBans", "GlobalBans.magics/items/skills/heroes/units"],
    docRefs: ["docs/rmg-kb/schema/global-bans.md"],
    mutation: "updateGlobalBans",
    picker: { source: "generatedCatalog", mode: "multi" },
  }),
  field({
    id: "template.valueOverrides",
    section: "templateSettings",
    scope: "template",
    path: "valueOverrides",
    label: "Value Overrides",
    kind: "objectArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Overrides generated economy/guard/AI values for selected content IDs.",
    valueMeaning: "`goodsValue`, `guardValue`, and `aiValue` override Core defaults for matching SID plus optional variant.",
    sourceEvidence: ["RandomMapTemplate.valueOverrides", "ContentValueOverride.sid/variant/goodsValue/guardValue/aiValue"],
    docRefs: ["docs/rmg-kb/schema/value-overrides.md"],
    mutation: "addValueOverride/removeValueOverride/updateValueOverride",
    picker: { source: "generatedCatalog", catalog: "rmgContent", mode: "single" },
  }),
  field({
    id: "template.variants",
    section: "templateSettings",
    scope: "template",
    path: "variants",
    label: "Variants",
    kind: "objectArray",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Alternative authored graphs/layouts under one template.",
    valueMeaning: "Each variant owns its zones, connections, orientation, border, and optional river settings.",
    sourceEvidence: ["RandomMapTemplate.variants", "Variant.zones/connections/orientation/border/river"],
    docRefs: ["docs/rmg-kb/schema/variant.md"],
    mutation: "addVariant/removeVariant",
  }),
  field({
    id: "gameRules.heroCountMin",
    section: "gameRules",
    scope: "template",
    path: "gameRules.heroCountMin",
    label: "Minimum Heroes",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Minimum hero count available to players.",
    valueMeaning: "Non-negative integer lower bound; should not exceed maximum hero count.",
    sourceEvidence: ["GameRules.heroCountMin"],
    docRefs: ["docs/rmg-kb/schema/game-rules.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
  }),
  field({
    id: "gameRules.heroCountMax",
    section: "gameRules",
    scope: "template",
    path: "gameRules.heroCountMax",
    label: "Maximum Heroes",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Maximum hero count available to players.",
    valueMeaning: "Non-negative integer upper bound; should be at least the minimum hero count.",
    sourceEvidence: ["GameRules.heroCountMax"],
    docRefs: ["docs/rmg-kb/schema/game-rules.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
  }),
  field({
    id: "gameRules.heroCountIncrement",
    section: "gameRules",
    scope: "template",
    path: "gameRules.heroCountIncrement",
    label: "Hero Count Increment",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Step value between allowed hero counts.",
    valueMeaning: "Official templates use it to constrain the selectable hero count ladder.",
    sourceEvidence: ["GameRules.heroCountIncrement"],
    docRefs: ["docs/rmg-kb/schema/game-rules.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
  }),
  field({
    id: "gameRules.heroHireBan",
    section: "gameRules",
    scope: "template",
    path: "gameRules.heroHireBan",
    label: "Ban Hero Hiring",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Disables tavern/hero hiring where supported.",
    valueMeaning: "`true` makes authored starting heroes much more important; common with final battle/single-hero designs.",
    sourceEvidence: ["GameRules.heroHireBan"],
    docRefs: ["docs/rmg-kb/schema/game-rules.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "gameRules.encounterHoles",
    section: "gameRules",
    scope: "template",
    path: "gameRules.encounterHoles",
    label: "Encounter Holes",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Enables encounter-hole behavior during content placement.",
    valueMeaning: "Global switch; per-zone ratios live under `zone.encounterHolesSettings`.",
    sourceEvidence: ["GameRules.encounterHoles", "EncounterHolesSettings.affectedEncounters/twoHoleEncounters"],
    docRefs: ["docs/rmg-kb/schema/game-rules.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "gameRules.disableFactionLaws",
    section: "gameRules",
    scope: "template",
    path: "gameRules.disableFactionLaws",
    label: "Disable Faction Laws",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Declared game-rule switch for faction-law systems.",
    valueMeaning: "Valid JSON field, but official templates did not use it in the inspected build.",
    sourceEvidence: ["GameRules.disableFactionLaws", "Official template usage scan: 0 occurrences."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "gameRules.disableMagicGuild",
    section: "gameRules",
    scope: "template",
    path: "gameRules.disableMagicGuild",
    label: "Disable Magic Guild",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Declared game-rule switch for magic guild availability.",
    valueMeaning: "Valid JSON field, but official templates did not use it in the inspected build.",
    sourceEvidence: ["GameRules.disableMagicGuild", "Official template usage scan: 0 occurrences."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "gameRules.disableMagicCustomLearning",
    section: "gameRules",
    scope: "template",
    path: "gameRules.disableMagicCustomLearning",
    label: "Disable Custom Magic Learning",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Declared game-rule switch for custom magic learning.",
    valueMeaning: "Valid JSON field, but official templates did not use it in the inspected build.",
    sourceEvidence: ["GameRules.disableMagicCustomLearning", "Official template usage scan: 0 occurrences."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "gameRules.tournamentRules",
    section: "gameRules",
    scope: "template",
    path: "gameRules.tournamentRules",
    label: "Tournament Rules",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Declared root switch associated with tournament-style templates.",
    valueMeaning: "Valid JSON field; pair with tournament win-condition params when authoring tournament maps.",
    sourceEvidence: ["GameRules.tournamentRules", "Official template usage scan: 1 template."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "gameRules.customAI",
    section: "gameRules",
    scope: "template",
    path: "gameRules.customAI",
    label: "Custom AI",
    kind: "string",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Declared custom AI selector.",
    valueMeaning: "Valid JSON field; no official usage found, so treat as freeform advanced data.",
    sourceEvidence: ["GameRules.customAI", "Official template usage scan: 0 occurrences."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
    picker: { source: "freeform", mode: "single" },
  }),
  field({
    id: "gameRules.factionLawsExpModifier",
    section: "gameRules",
    scope: "template",
    path: "gameRules.factionLawsExpModifier",
    label: "Faction Laws XP Modifier",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Experience modifier for faction-law behavior.",
    valueMeaning: "Finite numeric multiplier/modifier copied by game-rule handling.",
    sourceEvidence: ["GameRules.factionLawsExpModifier", "Official template usage scan: 15 templates."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
    validation: { finite: true },
  }),
  field({
    id: "gameRules.astrologyExpModifier",
    section: "gameRules",
    scope: "template",
    path: "gameRules.astrologyExpModifier",
    label: "Astrology XP Modifier",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Experience modifier for astrology behavior.",
    valueMeaning: "Finite numeric multiplier/modifier copied by game-rule handling.",
    sourceEvidence: ["GameRules.astrologyExpModifier", "Official template usage scan: 17 templates."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
    validation: { finite: true },
  }),
  field({
    id: "gameRules.bonuses",
    section: "gameRules",
    scope: "template",
    path: "gameRules.bonuses",
    label: "Map Bonuses",
    kind: "objectArray",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Map bonus objects copied into generated map settings.",
    valueMeaning: "Opaque `MapBonus[]` until the bonus DB schema is modeled; pick IDs from Core bonus data when possible.",
    sourceEvidence: ["GameRules.bonuses", "ContentPlacer.SetGameRules copies bonuses to map settings.", "Official template usage scan: 21 templates."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
    picker: { source: "generatedCatalog", mode: "multi" },
    validation: { reference: "mapBonus", note: "Opaque advanced object until map-bonus catalog schema is fully typed." },
  }),
  field({
    id: "winConditions.preset",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions",
    label: "Win Condition Preset",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "derived",
    description: "Named editor preset that expands to low-level win-condition fields.",
    valueMeaning: "Use presets to keep `displayWinCondition` and win-condition parameters coherent.",
    sourceEvidence: ["src/core/rmg/winConditions.ts", "Official `displayWinCondition` values map to named presets."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    picker: { source: "winConditionPresets", mode: "single" },
    validation: { allowedValues: WIN_CONDITION_PRESET_IDS },
  }),
  field({
    id: "winConditions.classic",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.classic",
    label: "Classic Victory",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables standard defeat-all/capture-all victory behavior.",
    valueMeaning: "`true` participates in the classic victory checks emitted by game-rule setup.",
    sourceEvidence: ["WinConditions.classic", "ContentPlacer.SetGameRules handles Classic."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.desertion",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.desertion",
    label: "Desertion Defeat",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables defeat/loss logic for low army value after a day threshold.",
    valueMeaning: "Use with `desertionDay` and `desertionValue`.",
    sourceEvidence: ["WinConditions.desertion", "ContentPlacer.SetGameRules handles Desertion."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.desertionDay",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.desertionDay",
    label: "Desertion Day",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Day threshold for desertion checks.",
    valueMeaning: "Integer day count; meaningful when `desertion` is enabled.",
    sourceEvidence: ["WinConditions.desertionDay"],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
    conditions: [{ field: "gameRules.winConditions.desertion", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.desertionValue",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.desertionValue",
    label: "Desertion Value",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Army/value threshold for desertion checks.",
    valueMeaning: "Non-negative value; meaningful when `desertion` is enabled.",
    sourceEvidence: ["WinConditions.desertionValue"],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
    conditions: [{ field: "gameRules.winConditions.desertion", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.heroLighting",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.heroLighting",
    label: "Hero Lighting",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables hero-lighting visibility behavior.",
    valueMeaning: "Uses `heroLightingDay` as timing parameter.",
    sourceEvidence: ["WinConditions.heroLighting", "ContentPlacer.SetGameRules handles HeroLighting."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.heroLightingDay",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.heroLightingDay",
    label: "Hero Lighting Day",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Day threshold for hero-lighting behavior.",
    valueMeaning: "Non-negative day count; meaningful when `heroLighting` is enabled.",
    sourceEvidence: ["WinConditions.heroLightingDay"],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
    conditions: [{ field: "gameRules.winConditions.heroLighting", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.lostStartCity",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.lostStartCity",
    label: "Lost Start City",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables loss/victory behavior around losing a starting city.",
    valueMeaning: "Uses `lostStartCityDay`; required for capital capture/hold styles.",
    sourceEvidence: ["WinConditions.lostStartCity", "ContentPlacer.SetGameRules handles LostStartCity."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.lostStartCityDay",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.lostStartCityDay",
    label: "Lost Start City Day",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Delay/day threshold for start-city loss logic.",
    valueMeaning: "Non-negative day count; meaningful when `lostStartCity` is enabled.",
    sourceEvidence: ["WinConditions.lostStartCityDay"],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
    conditions: [{ field: "gameRules.winConditions.lostStartCity", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.lostStartHero",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.lostStartHero",
    label: "Lost Start Hero",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables loss/victory behavior around losing the starting hero.",
    valueMeaning: "Commonly used by final-battle and tournament presets.",
    sourceEvidence: ["WinConditions.lostStartHero", "ContentPlacer.SetGameRules handles LostStartHero."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.gladiatorArena",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.gladiatorArena",
    label: "Gladiator Arena",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables final-battle arena behavior.",
    valueMeaning: "Use with arena registration, delay, count-day, and champion-selection parameters.",
    sourceEvidence: ["WinConditions.gladiatorArena", "ContentPlacer.SetGameRules handles GladiatorArena."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.gladiatorArenaDaysDelayStart",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.gladiatorArenaDaysDelayStart",
    label: "Arena Start Delay",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Day delay before arena/final-battle logic starts.",
    valueMeaning: "Non-negative day count; meaningful when arena-style conditions are enabled.",
    sourceEvidence: ["WinConditions.gladiatorArenaDaysDelayStart"],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
    conditions: [{ field: "gameRules.winConditions.gladiatorArena", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.gladiatorArenaCountDay",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.gladiatorArenaCountDay",
    label: "Arena Count Day",
    kind: "integer",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Arena/final-battle day-count parameter.",
    valueMeaning: "Non-negative day count used by gladiator/final battle settings.",
    sourceEvidence: ["WinConditions.gladiatorArenaCountDay"],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
    conditions: [{ field: "gameRules.winConditions.gladiatorArena", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.championSelectRule",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.championSelectRule",
    label: "Champion Select Rule",
    kind: "string",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Selects the hero/champion source for arena-style battles.",
    valueMeaning: "Official presets use `StartHero`.",
    sourceEvidence: ["WinConditions.championSelectRule", "Official presets use StartHero."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    picker: { source: "freeform", mode: "single" },
  }),
  field({
    id: "winConditions.cityHold",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.cityHold",
    label: "City Hold",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Declared city-hold victory flag.",
    valueMeaning: "Pair with a main object marked `holdCityWinCon`; runtime emission was not found in inspected `SetGameRules`.",
    sourceEvidence: ["WinConditions.cityHold", "MainObject.holdCityWinCon official usage scan: 8 objects in 5 templates.", "ContentPlacer.SetGameRules inspected paths did not emit cityHold."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.cityHoldDays",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.cityHoldDays",
    label: "City Hold Days",
    kind: "integer",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Number of days a marked city must be held.",
    valueMeaning: "Meaningful when `cityHold` is enabled and a main object is marked as the hold target.",
    sourceEvidence: ["WinConditions.cityHoldDays", "Official City Hold preset uses 3 days."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 0 },
    conditions: [{ field: "gameRules.winConditions.cityHold", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.tournament",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.tournament",
    label: "Tournament",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Declared tournament victory flag.",
    valueMeaning: "Pair with tournament points/days/announce-days and root `gameRules.tournamentRules`.",
    sourceEvidence: ["WinConditions.tournament", "Official Tournament preset uses tournament params.", "ContentPlacer.SetGameRules inspected paths did not emit tournament directly."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateTemplateSettings",
  }),
  field({
    id: "winConditions.tournamentPointsToWin",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.tournamentPointsToWin",
    label: "Tournament Points To Win",
    kind: "integer",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Tournament match points needed for victory.",
    valueMeaning: "Positive integer; meaningful when `tournament` is enabled.",
    sourceEvidence: ["WinConditions.tournamentPointsToWin", "Official Tournament preset uses 2."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    validation: { integer: true, min: 1 },
    conditions: [{ field: "gameRules.winConditions.tournament", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.tournamentDays",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.tournamentDays",
    label: "Tournament Days",
    kind: "numberArray",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Tournament day sequence.",
    valueMeaning: "Official preset uses repeated day windows; keep array length aligned with tournament design.",
    sourceEvidence: ["WinConditions.tournamentDays", "Official Tournament preset uses [3, 3, 3]."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    conditions: [{ field: "gameRules.winConditions.tournament", operator: "equals", value: true }],
  }),
  field({
    id: "winConditions.tournamentAnnounceDays",
    section: "winConditions",
    scope: "template",
    path: "gameRules.winConditions.tournamentAnnounceDays",
    label: "Tournament Announce Days",
    kind: "numberArray",
    editLevel: "advanced",
    sourceStatus: "declaredUnverifiedRuntime",
    description: "Announcement days for tournament rounds.",
    valueMeaning: "Official preset uses [7, 14, 21].",
    sourceEvidence: ["WinConditions.tournamentAnnounceDays", "Official Tournament preset uses [7, 14, 21]."],
    docRefs: ["docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateTemplateSettings",
    conditions: [{ field: "gameRules.winConditions.tournament", operator: "equals", value: true }],
  }),
  field({
    id: "zone.name",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].name",
    label: "Zone Name",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Variant-local zone identifier.",
    valueMeaning: "References from connections, roads, rules, and graph tools resolve by this name.",
    sourceEvidence: ["Zone.name", "Connection.from/to reference zone names."],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "addZone/removeZone/renameZone/cloneZone",
    validation: { required: true, nonEmpty: true, reference: "zone" },
  }),
  field({
    id: "zone.size",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].size",
    label: "Zone Size",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Relative zone size used by layout generation.",
    valueMeaning: "Non-negative numeric area weight; official templates commonly use small integers.",
    sourceEvidence: ["Zone.size"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "zone.layout",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].layout",
    label: "Zone Layout",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "References a root `zoneLayouts` entry.",
    valueMeaning: "Controls terrain fill, lakes, elevation, road cluster area, and encounter/resource terrain fractions.",
    sourceEvidence: ["Zone.layout", "RandomMapTemplate.zoneLayouts"],
    docRefs: ["docs/rmg-kb/schema/zone.md", "docs/rmg-kb/schema/zone-layout.md"],
    mutation: "updateZoneSettings/addZoneLayout/removeZoneLayout/updateZoneLayout",
    picker: { source: "localTemplate", mode: "single" },
    validation: { reference: "zoneLayout" },
  }),
  field({
    id: "zone.mainObjects",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].mainObjects",
    label: "Main Objects",
    kind: "objectArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Primary objects that define starts, cities, abandoned outposts, and arena anchors.",
    valueMeaning: "Main objects are special authored anchors with ownership, faction, placement, guard, and win-condition flags.",
    sourceEvidence: ["Zone.mainObjects", "MainObject.type includes City/Spawn/AbandonedOutpost/GladiatorArena."],
    docRefs: ["docs/rmg-kb/schema/main-object.md", "docs/rmg/zones.md"],
    mutation: "addMainObject/removeMainObject/updateMainObject",
  }),
  field({
    id: "mainObject.type",
    section: "zones",
    scope: "mainObject",
    path: "variants[].zones[].mainObjects[].type",
    label: "Main Object Type",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Main object archetype.",
    valueMeaning: "`Spawn` starts players/heroes, `City` places towns, `AbandonedOutpost` and `GladiatorArena` are special anchors.",
    sourceEvidence: ["MainObject.type", "MainObjectType enum in inspected source."],
    docRefs: ["docs/rmg-kb/schema/main-object.md"],
    mutation: "updateMainObject",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: MAIN_OBJECT_TYPES },
  }),
  field({
    id: "mainObject.spawn",
    section: "zones",
    scope: "mainObject",
    path: "variants[].zones[].mainObjects[].spawn",
    label: "Spawn Player",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Player start reference for spawn objects.",
    valueMeaning: "`Player1` through `Player8`; use on spawn zones/objects that should belong to a starting player.",
    sourceEvidence: ["MainObject.spawn", "PLAYER_REFS supports Player1 through Player8."],
    docRefs: ["docs/rmg-kb/schema/main-object.md"],
    mutation: "updateMainObject",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: PLAYER_REFS, reference: "player" },
    conditions: [{ field: "type", operator: "equals", value: "Spawn" }],
  }),
  field({
    id: "mainObject.owner",
    section: "zones",
    scope: "mainObject",
    path: "variants[].zones[].mainObjects[].owner",
    label: "Owner",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Initial owner for a main object.",
    valueMeaning: "Usually one of `Player1` through `Player8`; absence or neutral handling depends on object type.",
    sourceEvidence: ["MainObject.owner", "PLAYER_REFS supports Player1 through Player8."],
    docRefs: ["docs/rmg-kb/schema/main-object.md"],
    mutation: "updateMainObject",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: PLAYER_REFS, reference: "player" },
  }),
  field({
    id: "mainObject.faction",
    section: "zones",
    scope: "mainObject",
    path: "variants[].zones[].mainObjects[].faction",
    label: "Faction Rule",
    kind: "rule",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Faction selection rule for the main object.",
    valueMeaning: "`FromList` selects from explicit faction SIDs; `Match` follows another authored faction source.",
    sourceEvidence: ["MainObject.faction", "FactionRule.type supports FromList/Match."],
    docRefs: ["docs/rmg-kb/schema/faction-rule.md", "docs/rmg-kb/schema/main-object.md"],
    mutation: "updateMainObject",
    picker: { source: "generatedCatalog", catalog: "factions", mode: "multi" },
    validation: { allowedValues: FACTION_RULE_TYPES, reference: "faction" },
  }),
  field({
    id: "mainObject.placement",
    section: "zones",
    scope: "mainObject",
    path: "variants[].zones[].mainObjects[].placement",
    label: "Placement",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Placement algorithm for the main object inside its zone.",
    valueMeaning: "Controls whether placement is uniform, centered, near a connection, or near another zone.",
    sourceEvidence: ["MainObject.placement", "MainObjectPlacement enum."],
    docRefs: ["docs/rmg-kb/schema/main-object.md"],
    mutation: "updateMainObject",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: MAIN_OBJECT_PLACEMENTS },
  }),
  field({
    id: "mainObject.holdCityWinCon",
    section: "zones",
    scope: "mainObject",
    path: "variants[].zones[].mainObjects[].holdCityWinCon",
    label: "City Hold Target",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Marks a city-like object as the target for city-hold win conditions.",
    valueMeaning: "Use with `winConditions.cityHold`; official templates use it on hold-city targets.",
    sourceEvidence: ["MainObject.holdCityWinCon", "Official usage scan: 8 objects in 5 templates."],
    docRefs: ["docs/rmg-kb/schema/main-object.md", "docs/rmg-kb/schema/win-conditions.md"],
    mutation: "updateMainObject",
  }),
  field({
    id: "zone.zoneBiome",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].zoneBiome",
    label: "Zone Biome Rule",
    kind: "rule",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Biome rule for the zone terrain itself.",
    valueMeaning: "`FromList` chooses from explicit biome SIDs; match rules follow zone/main-object context.",
    sourceEvidence: ["Zone.zoneBiome", "BiomeRule.type supports FromList/MatchZone/MatchMainObject."],
    docRefs: ["docs/rmg-kb/schema/biome-rule.md", "docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    picker: { source: "generatedCatalog", catalog: "biomes", mode: "multi" },
    validation: { allowedValues: BIOME_RULE_TYPES, reference: "biome" },
  }),
  field({
    id: "zone.contentBiome",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].contentBiome",
    label: "Content Biome Rule",
    kind: "rule",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Biome rule used for content placement.",
    valueMeaning: "Can intentionally differ from terrain biome for content theming.",
    sourceEvidence: ["Zone.contentBiome", "BiomeRule.type supports FromList/MatchZone/MatchMainObject."],
    docRefs: ["docs/rmg-kb/schema/biome-rule.md", "docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    picker: { source: "generatedCatalog", catalog: "biomes", mode: "multi" },
    validation: { allowedValues: BIOME_RULE_TYPES, reference: "biome" },
  }),
  field({
    id: "zone.metaObjectsBiome",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].metaObjectsBiome",
    label: "Meta Objects Biome Rule",
    kind: "rule",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Biome rule used for meta-object placement.",
    valueMeaning: "Advanced terrain/content styling control.",
    sourceEvidence: ["Zone.metaObjectsBiome", "BiomeRule.type supports FromList/MatchZone/MatchMainObject."],
    docRefs: ["docs/rmg-kb/schema/biome-rule.md", "docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    picker: { source: "generatedCatalog", catalog: "biomes", mode: "multi" },
    validation: { allowedValues: BIOME_RULE_TYPES, reference: "biome" },
  }),
  field({
    id: "zone.crossroadsPosition",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].crossroadsPosition",
    label: "Crossroads Position",
    kind: "number",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Controls authored crossroads placement bias inside the zone.",
    valueMeaning: "Finite numeric parameter interpreted by zone/road generation.",
    sourceEvidence: ["Zone.crossroadsPosition"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    validation: { finite: true },
  }),
  field({
    id: "zone.guardedContentPool",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardedContentPool",
    label: "Guarded Content Pools",
    kind: "stringArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Alternative pool names for guarded content generation.",
    valueMeaning: "This is a sampled list of pool alternatives; the generator chooses among named pools rather than merging every entry.",
    sourceEvidence: ["Zone.guardedContentPool", "C# schema declares string[] pool preset alternatives."],
    docRefs: ["docs/rmg-kb/schema/zone.md", "docs/rmg/content-pools.md"],
    mutation: "setZoneContentPools",
    picker: { source: "localTemplate", mode: "sampledAlternatives" },
    validation: { reference: "contentPool" },
    sampledAlternative: true,
  }),
  field({
    id: "zone.unguardedContentPool",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].unguardedContentPool",
    label: "Unguarded Content Pools",
    kind: "stringArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Alternative pool names for unguarded content generation.",
    valueMeaning: "This is a sampled list of pool alternatives; use it for ambient pickups and low-danger objects.",
    sourceEvidence: ["Zone.unguardedContentPool", "C# schema declares string[] pool preset alternatives."],
    docRefs: ["docs/rmg-kb/schema/zone.md", "docs/rmg/content-pools.md"],
    mutation: "setZoneContentPools",
    picker: { source: "localTemplate", mode: "sampledAlternatives" },
    validation: { reference: "contentPool" },
    sampledAlternative: true,
  }),
  field({
    id: "zone.resourcesContentPool",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].resourcesContentPool",
    label: "Resource Content Pools",
    kind: "stringArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Alternative pool names for resource content generation.",
    valueMeaning: "This is a sampled list of pool alternatives for zone resource budget placement.",
    sourceEvidence: ["Zone.resourcesContentPool", "C# schema declares string[] pool preset alternatives."],
    docRefs: ["docs/rmg-kb/schema/zone.md", "docs/rmg/content-pools.md"],
    mutation: "setZoneContentPools",
    picker: { source: "localTemplate", mode: "sampledAlternatives" },
    validation: { reference: "contentPool" },
    sampledAlternative: true,
  }),
  field({
    id: "zone.contentCountLimits",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].contentCountLimits",
    label: "Content Count Limit Presets",
    kind: "stringArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Alternative content-count-limit preset names.",
    valueMeaning: "Sampled preset alternatives that limit specific content/list occurrence counts.",
    sourceEvidence: ["Zone.contentCountLimits", "ContentCountLimitPreset.limits"],
    docRefs: ["docs/rmg-kb/schema/content-count-limit-preset.md", "docs/rmg-kb/schema/zone.md"],
    mutation: "setZoneContentCountLimitPresets",
    picker: { source: "localTemplate", mode: "sampledAlternatives" },
    validation: { reference: "contentCountLimitPreset" },
    sampledAlternative: true,
  }),
  field({
    id: "zone.guardedContentValue",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardedContentValue",
    label: "Guarded Content Value",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Fixed value budget for guarded content.",
    valueMeaning: "Non-negative budget used alongside or instead of per-area budget.",
    sourceEvidence: ["Zone.guardedContentValue"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "setZoneContentBudgets",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "zone.guardedContentValuePerArea",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardedContentValuePerArea",
    label: "Guarded Value Per Area",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Area-scaled guarded content budget.",
    valueMeaning: "Non-negative per-area value multiplied by zone area/size semantics.",
    sourceEvidence: ["Zone.guardedContentValuePerArea"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "setZoneContentBudgets",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "zone.unguardedContentValue",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].unguardedContentValue",
    label: "Unguarded Content Value",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Fixed value budget for unguarded content.",
    valueMeaning: "Non-negative budget for unguarded generated objects.",
    sourceEvidence: ["Zone.unguardedContentValue"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "setZoneContentBudgets",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "zone.resourcesValue",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].resourcesValue",
    label: "Resources Value",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Fixed value budget for resource objects.",
    valueMeaning: "Non-negative budget for resources.",
    sourceEvidence: ["Zone.resourcesValue"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "setZoneContentBudgets",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "zone.guardMultiplier",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardMultiplier",
    label: "Guard Multiplier",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Multiplier applied to zone guard strength.",
    valueMeaning: "Finite numeric multiplier; higher values increase generated guard difficulty.",
    sourceEvidence: ["Zone.guardMultiplier"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    validation: { finite: true },
  }),
  field({
    id: "zone.guardCutoffValue",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardCutoffValue",
    label: "Guard Cutoff Value",
    kind: "number",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Guard-value cutoff controlling whether content receives guards.",
    valueMeaning: "Finite numeric threshold.",
    sourceEvidence: ["Zone.guardCutoffValue"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    validation: { finite: true },
  }),
  field({
    id: "zone.guardRandomization",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardRandomization",
    label: "Guard Randomization",
    kind: "number",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Randomization magnitude for generated zone guards.",
    valueMeaning: "Finite numeric amount; official templates use it as a guard variance parameter.",
    sourceEvidence: ["Zone.guardRandomization", "Official usage included zone/main-object/connection guard randomization fields."],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    validation: { finite: true },
  }),
  field({
    id: "zone.guardWeeklyIncrement",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardWeeklyIncrement",
    label: "Guard Weekly Increment",
    kind: "number",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Weekly growth applied to generated guards.",
    valueMeaning: "Finite numeric increment used to scale guards over time.",
    sourceEvidence: ["Zone.guardWeeklyIncrement"],
    docRefs: ["docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    validation: { finite: true },
  }),
  field({
    id: "zone.guardReactionDistribution",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].guardReactionDistribution",
    label: "Guard Reaction Distribution",
    kind: "numberArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Six weights for generated guard reactions.",
    valueMeaning: "Slots are Aggressive, Negative, Common, Friendly, Peaceful, Docile in that exact order.",
    sourceEvidence: ["Zone.guardReactionDistribution", "GuardReaction enum has 6 values.", "Official scan: 902 zones use six-slot arrays."],
    docRefs: ["docs/rmg-kb/schema/zone.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
    mutation: "updateZoneSettings",
    validation: { exactLength: 6, min: 0, allowedValues: GUARD_REACTIONS, note: "Array values are weights; allowedValues documents slot labels." },
  }),
  field({
    id: "zone.encounterHolesSettings",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].encounterHolesSettings",
    label: "Encounter Holes Settings",
    kind: "object",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Per-zone encounter-hole ratios.",
    valueMeaning: "`affectedEncounters` and `twoHoleEncounters` are float ratios used when root `encounterHoles` is enabled.",
    sourceEvidence: ["Zone.encounterHolesSettings", "EncounterHolesSettings.affectedEncounters/twoHoleEncounters", "Official usage scan: 163 zones in 2 templates."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md", "docs/rmg-kb/schema/zone.md"],
    mutation: "updateZoneSettings",
    conditions: [{ field: "gameRules.encounterHoles", operator: "equals", value: true }],
  }),
  field({
    id: "zone.mandatoryContent",
    section: "zones",
    scope: "zone",
    path: "variants[].zones[].mandatoryContent",
    label: "Mandatory Content Presets",
    kind: "stringArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Alternative mandatory-content preset names for a zone.",
    valueMeaning: "Sampled preset alternatives; each selected preset contains objects that must be placed.",
    sourceEvidence: ["Zone.mandatoryContent", "MandatoryContentPreset.content"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-preset.md", "docs/rmg-kb/schema/zone.md"],
    mutation: "setZoneMandatoryContentPresets",
    picker: { source: "localTemplate", mode: "sampledAlternatives" },
    validation: { reference: "mandatoryContentPreset" },
    sampledAlternative: true,
  }),
  field({
    id: "connection.name",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].name",
    label: "Connection Name",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Variant-local connection identifier.",
    valueMeaning: "Road targets and placement rules can reference connection names.",
    sourceEvidence: ["Connection.name", "RoadTarget.type Connection uses args to reference connection."],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "addConnection/removeConnection/renameConnection",
    validation: { required: true, nonEmpty: true, reference: "connection" },
  }),
  field({
    id: "connection.from",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].from",
    label: "From Zone",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "First endpoint zone name.",
    valueMeaning: "Must resolve to a zone in the same variant.",
    sourceEvidence: ["Connection.from"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionEndpoints",
    picker: { source: "localTemplate", mode: "single" },
    validation: { required: true, nonEmpty: true, reference: "zone" },
  }),
  field({
    id: "connection.to",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].to",
    label: "To Zone",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Second endpoint zone name.",
    valueMeaning: "Must resolve to a zone in the same variant.",
    sourceEvidence: ["Connection.to"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionEndpoints",
    picker: { source: "localTemplate", mode: "single" },
    validation: { required: true, nonEmpty: true, reference: "zone" },
  }),
  field({
    id: "connection.connectionType",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].connectionType",
    label: "Connection Type",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Connection behavior archetype.",
    valueMeaning: "`Direct` creates direct passage, `Portal` uses portal placement, `GladiatorArena`/`Proximity` have special semantics.",
    sourceEvidence: ["Connection.connectionType", "ConnectionType enum."],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionType",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: CONNECTION_TYPES },
  }),
  field({
    id: "connection.length",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].length",
    label: "Connection Length",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Distance/length parameter for generated connection geometry.",
    valueMeaning: "Finite non-negative length-like value interpreted by connection placement.",
    sourceEvidence: ["Connection.length"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "connection.portalFromEnabled",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].portalFromEnabled",
    label: "Portal From Enabled",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables portal placement on the `from` side.",
    valueMeaning: "Meaningful primarily for portal-style connections.",
    sourceEvidence: ["Connection.portalFromEnabled"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    conditions: [{ field: "connectionType", operator: "equals", value: "Portal" }],
  }),
  field({
    id: "connection.portalToEnabled",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].portalToEnabled",
    label: "Portal To Enabled",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Enables portal placement on the `to` side.",
    valueMeaning: "Meaningful primarily for portal-style connections.",
    sourceEvidence: ["Connection.portalToEnabled"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    conditions: [{ field: "connectionType", operator: "equals", value: "Portal" }],
  }),
  field({
    id: "connection.guardZone",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].guardZone",
    label: "Guard Zone",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Zone whose biome/context is used for connection guard placement.",
    valueMeaning: "Should resolve to an endpoint or nearby zone depending on generator rules.",
    sourceEvidence: ["Connection.guardZone"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    picker: { source: "localTemplate", mode: "single" },
    validation: { reference: "zone" },
  }),
  field({
    id: "connection.guardValue",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].guardValue",
    label: "Guard Value",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Guard strength value for the connection.",
    valueMeaning: "Non-negative budget/value for guarding a passage/gate/portal.",
    sourceEvidence: ["Connection.guardValue"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "connection.guardWeeklyIncrement",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].guardWeeklyIncrement",
    label: "Guard Weekly Increment",
    kind: "number",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Weekly growth applied to connection guards.",
    valueMeaning: "Finite numeric increment for guards on connection content.",
    sourceEvidence: ["Connection.guardWeeklyIncrement"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    validation: { finite: true },
  }),
  field({
    id: "connection.guardReaction",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].guardReaction",
    label: "Guard Reaction",
    kind: "enum",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Explicit reaction assigned to connection guards.",
    valueMeaning: "One of Aggressive, Negative, Common, Friendly, Peaceful, Docile.",
    sourceEvidence: ["Connection.guardReaction", "GuardReaction enum."],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: GUARD_REACTIONS },
  }),
  field({
    id: "connection.guardEscape",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].guardEscape",
    label: "Guard Escape",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Allows/disallows escape behavior for connection guards.",
    valueMeaning: "Boolean guard behavior switch.",
    sourceEvidence: ["Connection.guardEscape"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
  }),
  field({
    id: "connection.guardMatchGroup",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].guardMatchGroup",
    label: "Guard Match Group",
    kind: "string",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Groups guards for matching/scaling behavior.",
    valueMeaning: "Freeform group token; preserve exact string.",
    sourceEvidence: ["Connection.guardMatchGroup"],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
  }),
  field({
    id: "connection.gatePlacement",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].gatePlacement",
    label: "Gate Placement",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Gate placement mode for guarded/gated connections.",
    valueMeaning: "`Random`, `Center`, or `NearZone`.",
    sourceEvidence: ["Connection.gatePlacement", "GatePlacement enum."],
    docRefs: ["docs/rmg-kb/schema/connection.md"],
    mutation: "updateConnectionSettings",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: GATE_PLACEMENTS },
  }),
  field({
    id: "connection.portalPlacementRulesFrom",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].portalPlacementRulesFrom",
    label: "Portal From Placement Rules",
    kind: "objectArray",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Placement-rule list for from-side portal objects.",
    valueMeaning: "Rules use placement types like MainObject, Crossroads, Connection, Road, and MandatoryContent.",
    sourceEvidence: ["Connection.portalPlacementRulesFrom", "PlacementRule.type enum."],
    docRefs: ["docs/rmg-kb/schema/connection.md", "docs/rmg-kb/schema/placement-rule.md"],
    mutation: "updateConnectionSettings",
    picker: { source: "enum", mode: "multi" },
    validation: { allowedValues: PLACEMENT_RULE_TYPES },
    conditions: [{ field: "connectionType", operator: "equals", value: "Portal" }],
  }),
  field({
    id: "connection.portalPlacementRulesTo",
    section: "connections",
    scope: "connection",
    path: "variants[].connections[].portalPlacementRulesTo",
    label: "Portal To Placement Rules",
    kind: "objectArray",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Placement-rule list for to-side portal objects.",
    valueMeaning: "Rules use placement types like MainObject, Crossroads, Connection, Road, and MandatoryContent.",
    sourceEvidence: ["Connection.portalPlacementRulesTo", "PlacementRule.type enum."],
    docRefs: ["docs/rmg-kb/schema/connection.md", "docs/rmg-kb/schema/placement-rule.md"],
    mutation: "updateConnectionSettings",
    picker: { source: "enum", mode: "multi" },
    validation: { allowedValues: PLACEMENT_RULE_TYPES },
    conditions: [{ field: "connectionType", operator: "equals", value: "Portal" }],
  }),
  field({
    id: "road.type",
    section: "roads",
    scope: "road",
    path: "variants[].zones[].roads[].type",
    label: "Road Type",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Road surface/type.",
    valueMeaning: "Official enum currently exposes Dirt and Stone.",
    sourceEvidence: ["RoadConfig.type", "RoadType enum."],
    docRefs: ["docs/rmg-kb/schema/road.md"],
    mutation: "addZoneRoad/updateZoneRoad/removeZoneRoad",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: ROAD_TYPES },
  }),
  field({
    id: "road.from",
    section: "roads",
    scope: "road",
    path: "variants[].zones[].roads[].from",
    label: "Road From Target",
    kind: "object",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Starting road target.",
    valueMeaning: "Target can be a crossroads, main object, connection, or mandatory-content entry.",
    sourceEvidence: ["RoadConfig.from", "RoadTargetConfig.type enum."],
    docRefs: ["docs/rmg-kb/schema/road.md", "docs/rmg-kb/schema/road-target.md"],
    mutation: "updateZoneRoad",
    validation: { reference: "mandatoryContentEntry" },
  }),
  field({
    id: "road.to",
    section: "roads",
    scope: "road",
    path: "variants[].zones[].roads[].to",
    label: "Road To Target",
    kind: "object",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Ending road target.",
    valueMeaning: "Target can be a crossroads, main object, connection, or mandatory-content entry.",
    sourceEvidence: ["RoadConfig.to", "RoadTargetConfig.type enum."],
    docRefs: ["docs/rmg-kb/schema/road.md", "docs/rmg-kb/schema/road-target.md"],
    mutation: "updateZoneRoad",
    validation: { reference: "mandatoryContentEntry" },
  }),
  field({
    id: "roadTarget.type",
    section: "roads",
    scope: "roadTarget",
    path: "variants[].zones[].roads[].from.type|to.type",
    label: "Road Target Type",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Kind of road endpoint.",
    valueMeaning: "`MainObject` generally points at a main-object index; `Connection` points at a connection name; `MandatoryContent` points at an authored mandatory entry.",
    sourceEvidence: ["RoadTargetConfig.type", "RoadTargetType enum."],
    docRefs: ["docs/rmg-kb/schema/road-target.md"],
    mutation: "updateZoneRoad",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: ROAD_TARGET_TYPES },
  }),
  field({
    id: "roadTarget.args",
    section: "roads",
    scope: "roadTarget",
    path: "variants[].zones[].roads[].from.args|to.args",
    label: "Road Target Args",
    kind: "stringArray",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Target-specific string arguments.",
    valueMeaning: "Args resolve differently by target type; preserve order exactly.",
    sourceEvidence: ["RoadTargetConfig.args", "RoadTargetType controls args interpretation."],
    docRefs: ["docs/rmg-kb/schema/road-target.md"],
    mutation: "updateZoneRoad",
  }),
  field({
    id: "contentPool.name",
    section: "contentPools",
    scope: "contentPool",
    path: "contentPools[].name",
    label: "Pool Name",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Template-local content pool identifier.",
    valueMeaning: "Zones reference pools by name in guarded/unguarded/resources pool alternatives.",
    sourceEvidence: ["ContentPoolConfig.name", "Zone.guardedContentPool/unguardedContentPool/resourcesContentPool reference pool names."],
    docRefs: ["docs/rmg-kb/schema/content-pool.md"],
    mutation: "addLocalContentPool/removeLocalContentPool/renameLocalContentPool/updateLocalContentPool",
    validation: { required: true, nonEmpty: true, reference: "contentPool" },
  }),
  field({
    id: "contentPool.valueDistribution",
    section: "contentPools",
    scope: "contentPool",
    path: "contentPools[].valueDistribution",
    label: "Value Distribution",
    kind: "object",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Distribution curve for selecting content values from a pool.",
    valueMeaning: "`priceBounds` and `weights` define weighted value buckets.",
    sourceEvidence: ["ContentPoolConfig.valueDistribution", "ValueDistributionConfig.priceBounds/weights"],
    docRefs: ["docs/rmg-kb/schema/content-pool.md"],
    mutation: "updateContentPoolValueDistribution",
  }),
  field({
    id: "contentPool.groups",
    section: "contentPools",
    scope: "contentPool",
    path: "contentPools[].groups",
    label: "Pool Groups",
    kind: "objectArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Weighted groups inside a pool.",
    valueMeaning: "The pool samples groups by weight, then uses included lists and direct content entries from the chosen group.",
    sourceEvidence: ["ContentPoolConfig.groups", "ContentPoolGroup.weight/includeLists/content"],
    docRefs: ["docs/rmg-kb/schema/content-pool.md"],
    mutation: "addContentPoolGroup/removeContentPoolGroup/moveContentPoolGroup/updateContentPoolGroup",
  }),
  field({
    id: "contentPool.group.weight",
    section: "contentPools",
    scope: "contentPoolGroup",
    path: "contentPools[].groups[].weight",
    label: "Group Weight",
    kind: "number",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Selection weight for a group inside a content pool.",
    valueMeaning: "Higher values make the group more likely to be selected among sibling groups.",
    sourceEvidence: ["ContentPoolGroup.weight"],
    docRefs: ["docs/rmg-kb/schema/content-pool.md"],
    mutation: "updateContentPoolGroup",
    validation: { finite: true, min: 0 },
  }),
  field({
    id: "contentPool.group.includeLists",
    section: "contentPools",
    scope: "contentPoolGroup",
    path: "contentPools[].groups[].includeLists",
    label: "Included Content Lists",
    kind: "stringArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Content-list names included by a pool group.",
    valueMeaning: "References root template lists and/or Core lists available through game data.",
    sourceEvidence: ["ContentPoolGroup.includeLists", "ContentList.name"],
    docRefs: ["docs/rmg-kb/schema/content-pool.md", "docs/rmg-kb/schema/content-list.md"],
    mutation: "updateContentPoolGroup",
    picker: { source: "localTemplate", mode: "multi" },
    validation: { reference: "contentList" },
  }),
  field({
    id: "contentPool.group.content",
    section: "contentPools",
    scope: "contentPoolGroup",
    path: "contentPools[].groups[].content",
    label: "Direct Weighted Content",
    kind: "contentWeightArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Direct weighted RMG content entries in a group.",
    valueMeaning: "Each entry references a valid RMG content SID, optional variant/biome, and selection weight.",
    sourceEvidence: ["ContentPoolGroup.content", "ContentWeight.sid/variant/biome/weight"],
    docRefs: ["docs/rmg-kb/schema/content-weight.md", "docs/rmg/content-pools.md"],
    mutation: "updateContentPoolGroup",
    picker: { source: "generatedCatalog", catalog: "rmgContent", mode: "weighted" },
    validation: { reference: "rmgContentSid" },
  }),
  field({
    id: "contentPool.bans",
    section: "contentPools",
    scope: "contentPool",
    path: "contentPools[].bans",
    label: "Pool Bans",
    kind: "contentIdArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Content IDs excluded from a specific pool.",
    valueMeaning: "Each ban references a SID plus optional variant.",
    sourceEvidence: ["ContentPoolConfig.bans", "ContentID.sid/variant"],
    docRefs: ["docs/rmg-kb/schema/content-pool.md"],
    mutation: "addContentPoolBan/removeContentPoolBan/moveContentPoolBan/updateContentPoolBan",
    picker: { source: "generatedCatalog", catalog: "rmgContent", mode: "multi" },
    validation: { reference: "rmgContentSid" },
  }),
  field({
    id: "contentList.name",
    section: "contentPools",
    scope: "contentList",
    path: "contentLists[].name",
    label: "Content List Name",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Template-local content-list identifier.",
    valueMeaning: "Pool groups and mandatory content entries can include lists by this name.",
    sourceEvidence: ["ContentList.name", "ContentPoolGroup.includeLists"],
    docRefs: ["docs/rmg-kb/schema/content-list.md"],
    mutation: "addContentList/removeContentList/renameContentList/updateContentList",
    validation: { required: true, nonEmpty: true, reference: "contentList" },
  }),
  field({
    id: "contentList.content",
    section: "contentPools",
    scope: "contentList",
    path: "contentLists[].content",
    label: "Content List Entries",
    kind: "contentWeightArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Weighted RMG content entries inside a reusable list.",
    valueMeaning: "Entries can point at artifacts, objects, spells, resources, and other content SIDs exposed by Core RMG content.",
    sourceEvidence: ["ContentList.content", "ContentWeight.sid/variant/biome/weight", "Generated RMG content catalog is built from Core.zip."],
    docRefs: ["docs/rmg-kb/schema/content-list.md", "docs/rmg-kb/schema/content-weight.md"],
    mutation: "updateContentList",
    picker: { source: "generatedCatalog", catalog: "rmgContent", mode: "weighted" },
    validation: { reference: "rmgContentSid" },
  }),
  field({
    id: "contentCountLimit.name",
    section: "contentPools",
    scope: "contentCountLimitPreset",
    path: "contentCountLimits[].name",
    label: "Count Limit Preset Name",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Template-local count-limit preset identifier.",
    valueMeaning: "Zones reference these presets by name through sampled alternatives.",
    sourceEvidence: ["ContentCountLimitPreset.name", "Zone.contentCountLimits"],
    docRefs: ["docs/rmg-kb/schema/content-count-limit-preset.md"],
    mutation: "addContentCountLimitPreset/removeContentCountLimitPreset/renameContentCountLimitPreset/updateContentCountLimitPreset",
    validation: { required: true, nonEmpty: true, reference: "contentCountLimitPreset" },
  }),
  field({
    id: "contentCountLimit.limits",
    section: "contentPools",
    scope: "contentCountLimitPreset",
    path: "contentCountLimits[].limits",
    label: "Count Limit Entries",
    kind: "objectArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "List/content IDs and maximum counts enforced by the preset.",
    valueMeaning: "Can cap included lists or direct content IDs by SID/variant/biome.",
    sourceEvidence: ["ContentCountLimitPreset.limits", "ContentCountLimit.includeLists/content/sid/variant/biome/maxCount"],
    docRefs: ["docs/rmg-kb/schema/content-count-limit-entry.md"],
    mutation: "updateContentCountLimitPreset",
    picker: { source: "generatedCatalog", catalog: "rmgContent", mode: "multi" },
  }),
  field({
    id: "mandatoryContent.name",
    section: "mandatoryContent",
    scope: "mandatoryContentPreset",
    path: "mandatoryContent[].name",
    label: "Mandatory Preset Name",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Template-local mandatory-content preset identifier.",
    valueMeaning: "Zones reference mandatory-content presets by name through sampled alternatives.",
    sourceEvidence: ["MandatoryContentPreset.name", "Zone.mandatoryContent"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-preset.md"],
    mutation: "addMandatoryContentPreset/removeMandatoryContentPreset/renameMandatoryContentPreset/updateMandatoryContentPreset",
    validation: { required: true, nonEmpty: true, reference: "mandatoryContentPreset" },
  }),
  field({
    id: "mandatoryContent.content",
    section: "mandatoryContent",
    scope: "mandatoryContentPreset",
    path: "mandatoryContent[].content",
    label: "Mandatory Entries",
    kind: "objectArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Objects that must be placed when a preset is selected.",
    valueMeaning: "Entries can include direct content SIDs, content lists, placement rules, ownership, guarding, and encounter flags.",
    sourceEvidence: ["MandatoryContentPreset.content", "MandatoryContent.sid/includeLists/rules/designatedEncounter/soloEncounter/isGuarded/isMine/owner"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-preset.md", "docs/rmg-kb/schema/mandatory-content-entry.md"],
    mutation: "updateMandatoryContentPreset",
  }),
  field({
    id: "mandatoryContent.entry.name",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].name",
    label: "Mandatory Entry Name",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Identifier for one mandatory content entry.",
    valueMeaning: "Road targets and placement rules can use this to refer to the entry.",
    sourceEvidence: ["MandatoryContent.name", "RoadTarget type MandatoryContent"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md", "docs/rmg-kb/schema/road-target.md"],
    mutation: "updateMandatoryContentPreset",
    validation: { reference: "mandatoryContentEntry" },
  }),
  field({
    id: "mandatoryContent.entry.includeLists",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].includeLists",
    label: "Included Lists",
    kind: "stringArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Content lists usable by this mandatory entry.",
    valueMeaning: "References root/local or Core content-list names.",
    sourceEvidence: ["MandatoryContent.includeLists", "ContentList.name"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md", "docs/rmg-kb/schema/content-list.md"],
    mutation: "updateMandatoryContentPreset",
    picker: { source: "localTemplate", mode: "multi" },
    validation: { reference: "contentList" },
  }),
  field({
    id: "mandatoryContent.entry.content",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].content",
    label: "Weighted Content Options",
    kind: "contentWeightArray",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Direct weighted content options for mandatory placement.",
    valueMeaning: "Used when the mandatory object can be one of several valid RMG content entries.",
    sourceEvidence: ["MandatoryContent.content", "ContentWeight.sid/variant/biome/weight"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md", "docs/rmg-kb/schema/content-weight.md"],
    mutation: "updateMandatoryContentPreset",
    picker: { source: "generatedCatalog", catalog: "rmgContent", mode: "weighted" },
    validation: { reference: "rmgContentSid" },
  }),
  field({
    id: "mandatoryContent.entry.sid",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].sid",
    label: "Direct Content SID",
    kind: "string",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Direct content SID for mandatory placement.",
    valueMeaning: "References a single Core RMG content object; optional variant can disambiguate variants.",
    sourceEvidence: ["MandatoryContent.sid", "MandatoryContent.variant"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md"],
    mutation: "updateMandatoryContentPreset",
    picker: { source: "generatedCatalog", catalog: "rmgContent", mode: "single" },
    validation: { reference: "rmgContentSid" },
  }),
  field({
    id: "mandatoryContent.entry.rules",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].rules",
    label: "Placement Rules",
    kind: "objectArray",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Placement rules for mandatory content.",
    valueMeaning: "Rules constrain position relative to roads, connections, main objects, crossroads, and other mandatory entries.",
    sourceEvidence: ["MandatoryContent.rules", "PlacementRule.type enum."],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md", "docs/rmg-kb/schema/placement-rule.md"],
    mutation: "updateMandatoryContentPreset",
    picker: { source: "enum", mode: "multi" },
    validation: { allowedValues: PLACEMENT_RULE_TYPES },
  }),
  field({
    id: "mandatoryContent.entry.designatedEncounter",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].designatedEncounter",
    label: "Designated Encounter",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Marks the entry as a designated encounter.",
    valueMeaning: "Affects encounter placement/guarding semantics.",
    sourceEvidence: ["MandatoryContent.designatedEncounter"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md"],
    mutation: "updateMandatoryContentPreset",
  }),
  field({
    id: "mandatoryContent.entry.soloEncounter",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].soloEncounter",
    label: "Solo Encounter",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Marks the entry as a solo encounter.",
    valueMeaning: "Separates the encounter from normal group placement.",
    sourceEvidence: ["MandatoryContent.soloEncounter"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md"],
    mutation: "updateMandatoryContentPreset",
  }),
  field({
    id: "mandatoryContent.entry.isGuarded",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].isGuarded",
    label: "Is Guarded",
    kind: "boolean",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Forces guarded placement semantics for the entry.",
    valueMeaning: "`true` means placement should receive/expect guard logic.",
    sourceEvidence: ["MandatoryContent.isGuarded"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md"],
    mutation: "updateMandatoryContentPreset",
  }),
  field({
    id: "mandatoryContent.entry.isMine",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].isMine",
    label: "Is Mine",
    kind: "boolean",
    editLevel: "advanced",
    sourceStatus: "declared",
    description: "Marks the mandatory object as a mine-like object.",
    valueMeaning: "Use with mine content SIDs and ownership settings.",
    sourceEvidence: ["MandatoryContent.isMine"],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md"],
    mutation: "updateMandatoryContentPreset",
  }),
  field({
    id: "mandatoryContent.entry.owner",
    section: "mandatoryContent",
    scope: "mandatoryContentEntry",
    path: "mandatoryContent[].content[].owner",
    label: "Owner",
    kind: "enum",
    editLevel: "firstClass",
    sourceStatus: "declared",
    description: "Owner assigned to the mandatory object.",
    valueMeaning: "Usually one of `Player1` through `Player8` when authored ownership is needed.",
    sourceEvidence: ["MandatoryContent.owner", "PLAYER_REFS supports Player1 through Player8."],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-entry.md"],
    mutation: "updateMandatoryContentPreset",
    picker: { source: "enum", mode: "single" },
    validation: { allowedValues: PLAYER_REFS, reference: "player" },
  }),
  field({
    id: "gameRules.uniqueMagicCostModifiers",
    section: "compatibility",
    scope: "template",
    path: "gameRules.uniqueMagicCostModifiers",
    label: "Unique Magic Cost Modifiers",
    kind: "objectArray",
    editLevel: "preserveOnly",
    sourceStatus: "sourceMismatch",
    description: "A game-rule field referenced by inspected placement code but not declared on inspected `GameRules`.",
    valueMeaning: "Round-trip if present, but do not generate new values until source drift is resolved.",
    sourceEvidence: ["ContentPlacer.SetGameRules references mapDesc.gameRules.uniqueMagicCostModifiers.", "Inspected GameRules.cs did not declare uniqueMagicCostModifiers.", "Official template scan found no usage."],
    docRefs: ["docs/rmg-kb/schema/misc-settings-compatibility.md"],
    compatibilityNote: "Preserve unknown/raw data only; no first-class authoring.",
  }),
  field({
    id: "connection.road",
    section: "compatibility",
    scope: "connection",
    path: "variants[].connections[].road",
    label: "Connection Road",
    kind: "boolean",
    editLevel: "compatibility",
    sourceStatus: "officialObservedOnly",
    description: "Observed official connection field for road behavior.",
    valueMeaning: "Official JSON uses it, but inspected `RandomMapTemplate.Connection` did not declare it; zone-local `roads[]` are the proven road authoring path.",
    sourceEvidence: ["Official template usage scan: connection.road in 923 connections / 39 templates.", "Inspected RandomMapTemplate.Connection did not include road."],
    docRefs: ["docs/rmg-kb/schema/connection.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
    compatibilityNote: "Expose in advanced/raw panel and round-trip; prefer zone `roads[]` for authored road editing.",
  }),
  field({
    id: "connection.simTurnSquad",
    section: "compatibility",
    scope: "connection",
    path: "variants[].connections[].simTurnSquad",
    label: "Simultaneous-Turn Squad",
    kind: "boolean",
    editLevel: "compatibility",
    sourceStatus: "officialObservedOnly",
    description: "Observed official connection flag, likely connected to simultaneous-turn behavior.",
    valueMeaning: "Round-trip/expose as advanced because inspected connection type did not declare it.",
    sourceEvidence: ["Official template usage scan: simTurnSquad in 430 connections / 47 templates.", "Inspected RandomMapTemplate.Connection did not include simTurnSquad."],
    docRefs: ["docs/rmg-kb/schema/connection.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
    compatibilityNote: "Preserve and allow advanced editing, but do not build validation assumptions beyond boolean shape.",
  }),
  field({
    id: "connection.guardRandomization",
    section: "compatibility",
    scope: "connection",
    path: "variants[].connections[].guardRandomization",
    label: "Connection Guard Randomization",
    kind: "number",
    editLevel: "compatibility",
    sourceStatus: "officialObservedOnly",
    description: "Observed official connection-level guard-randomization field.",
    valueMeaning: "Appears analogous to zone/main-object guard randomization, but inspected connection schema did not declare it.",
    sourceEvidence: ["Official template scan found connection-level guardRandomization usage.", "Inspected RandomMapTemplate.Connection did not include guardRandomization."],
    docRefs: ["docs/rmg-kb/schema/connection.md", "docs/rmg-kb/schema/misc-settings-compatibility.md"],
    validation: { finite: true },
    compatibilityNote: "Round-trip and advanced edit only until runtime handling is verified.",
  }),
  field({
    id: "zone.mandatoryContent.legacyScalar",
    section: "compatibility",
    scope: "zone",
    path: "variants[].zones[].mandatoryContent",
    label: "Legacy Scalar Mandatory Preset",
    kind: "string",
    editLevel: "preserveOnly",
    sourceStatus: "sourceMismatch",
    description: "Legacy/scalar shape seen in old samples where C# declares a string array.",
    valueMeaning: "Normalize to string array for new authoring; preserve raw shape only when reading old data.",
    sourceEvidence: ["Zone.mandatoryContent is declared as string[].", "Legacy scalar fixture is retained in mutation invariants for compatibility."],
    docRefs: ["docs/rmg-kb/schema/mandatory-content-preset.md", "docs/rmg/validation-and-gaps.md"],
    compatibilityNote: "New editor writes string arrays.",
  }),
  field({
    id: "zone.contentCountLimits.legacyScalar",
    section: "compatibility",
    scope: "zone",
    path: "variants[].zones[].contentCountLimits",
    label: "Legacy Scalar Count Limit Preset",
    kind: "string",
    editLevel: "preserveOnly",
    sourceStatus: "sourceMismatch",
    description: "Legacy/scalar shape seen in old samples where C# declares a string array.",
    valueMeaning: "Normalize to string array for new authoring; preserve raw shape only when reading old data.",
    sourceEvidence: ["Zone.contentCountLimits is declared as string[].", "Legacy scalar fixture is retained in mutation invariants for compatibility."],
    docRefs: ["docs/rmg-kb/schema/content-count-limit-preset.md", "docs/rmg/validation-and-gaps.md"],
    compatibilityNote: "New editor writes string arrays.",
  }),
] as const satisfies readonly EditorFieldMetadata[];

const FIELDS_BY_ID = new Map(EDITOR_SCHEMA_FIELDS.map((item) => [item.id, item]));

export const EDITOR_SCHEMA: EditorSchema = {
  version: 1,
  sections: EDITOR_SCHEMA_SECTIONS,
  fields: EDITOR_SCHEMA_FIELDS,
};

export function getEditorSchema(): EditorSchema {
  return EDITOR_SCHEMA;
}

export function listEditorFields(section?: EditorSchemaSectionId): readonly EditorFieldMetadata[] {
  if (!section) {
    return EDITOR_SCHEMA_FIELDS;
  }
  return EDITOR_SCHEMA_FIELDS.filter((fieldMetadata) => fieldMetadata.section === section);
}

export function getEditorField(id: string): EditorFieldMetadata | undefined {
  return FIELDS_BY_ID.get(id);
}

export function listEditorFieldsByEditLevel(editLevel: EditorFieldEditLevel): readonly EditorFieldMetadata[] {
  return EDITOR_SCHEMA_FIELDS.filter((fieldMetadata) => fieldMetadata.editLevel === editLevel);
}

export function listEditorFieldsBySourceStatus(status: EditorFieldSourceStatus): readonly EditorFieldMetadata[] {
  return EDITOR_SCHEMA_FIELDS.filter((fieldMetadata) => fieldMetadata.sourceStatus === status);
}
